apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: registry.ng.bluemix.net/takara/webapp1:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 31520
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-app
spec:
  tls:
  - hosts:
    - mycluster2-658797.us-south.containers.mybluemix.net
    secretName: mycluster2-658797
  rules:
  - host: mycluster2-658797.us-south.containers.mybluemix.net
    http:
      paths:
      - path: /
        backend:
          serviceName: web-app
          servicePort: 3000
