# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # VirtualBoxで起動する仮想サーバーのOS
  config.vm.box = "ubuntu/xenial64"

  # GlusterFSのバージョン
  glusterfs_version = "3.12"

  # GlusterFSのサーバーの構成と起動
  # ホスト名 gluster-1〜gluster-3の３つのホストを起動するループを回します。
  # 172.20.11〜13のプライベートIPアドレスを付与、
  # この３つのホストには、それぞれ 80GiBのデータ保存用のディスクを付与します。
  # このデータ保存用の仮想ディスクは、
  # 仮想サーバーが起動したら、GlusferFSのリポジトリからインストールします。

  (1..3).each do |i|
    config.vm.define vm_name = "gluster-#{i}" do |config|
      config.cache.scope = :box
      config.vm.hostname = vm_name

      # MinikubeからアクセスできるIPアドレス
      private_ip = "172.20.1.#{i+10}"
      config.vm.network "private_network", ip: private_ip
      
      # データ保存用ディスクの増設
      config.vm.provider :virtualbox do |p|
        vdisk = "vdisk/sdb-#{i}.vdi"
        if not File.exist?(vdisk) then
          p.customize [
            'createmedium', 'disk',
            '--filename', vdisk,
            '--format', 'VDI',
            '--size', 80 * 1024]
        end
        # Gluster用デバイスを定義
        p.customize [
          'storageattach', :id,
          '--storagectl', 'SCSI',
          '--port', 2,
          '--device', 0,
          '--type', 'hdd',
          '--medium', vdisk]
      end

      # 仮想サーバー起動後のGlusterFSのインストール
      config.vm.provision "shell", inline: <<-SHELL
         export DEBIAN_FRONTEND=noninteractive 
         apt-get update && apt-get install -yq python-software-properties
         add-apt-repository ppa:gluster/glusterfs-#{glusterfs_version}
         apt-get update && apt-get install -yq glusterfs-server thin-provisioning-tools
         cp /vagrant/ssh/id_rsa.pub /root/.ssh/authorized_keys
      SHELL
    end
  end


  # Heketiのインストールと GlusterFSのクラスタ設定
  # IPアドレス　172.20.1.10で起動します。
  config.vm.define vm_name = "heketi" do |config|
    config.cache.scope = :box
    config.vm.hostname = vm_name
    config.vm.network "private_network", ip: "172.20.1.10"
    
    # 仮想サーバー起動後のインストールとクラスタの設定のシェルです。
    # こちらにもIPアドレスが入っているので、合わせて修正をお願いします。
    config.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive  
      apt-get update && apt-get install -yq python-software-properties curl
      add-apt-repository ppa:gluster/glusterfs-#{glusterfs_version}
      apt-get update && apt-get install -yq glusterfs-client
      cp /vagrant/ssh/id_rsa /root/.ssh/id_rsa
      chmod 0600 /root/.ssh/id_rsa
      cp /vagrant/ssh/id_rsa /home/vagrant/.ssh/id_rsa
      chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
      chmod 0600 /home/vagrant/.ssh/id_rsa
      ssh -o 'StrictHostKeyChecking no' root@172.20.1.11 hostname
      ssh -o 'StrictHostKeyChecking no' root@172.20.1.12 hostname
      ssh -o 'StrictHostKeyChecking no' root@172.20.1.13 hostname
      curl -s -LO https://github.com/heketi/heketi/releases/download/1.0.1/heketi-1.0.1.linux.amd64.tar.gz
      tar xzvf heketi-1.0.1.linux.amd64.tar.gz
      cp /vagrant/heketi/heketi.json /home/vagrant/heketi/heketi.json
      cd /home/vagrant/heketi/
      nohup ./heketi -config heketi.json > heketi.log &
    SHELL
  end
end
