apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websphere
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: websphere
    spec:
      restartPolicy: Always
      hostname: app
      containers:	     
      - name: websphere
        image: maho/javaapp:1.0
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: websphere
spec:
  type: NodePort
  selector:
    app: websphere
  ports:
  - protocol: TCP
    port: 9080
    nodePort: 31980
