apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ro-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ro-cache
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: kvs-vol
      volumes:
      - name: kvs-vol
        emptyDir: {}	
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: ro-cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
