apiVersion: v1
kind: PersistentVolume
metadata:
  name: takara
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  glusterfs:
    endpoints: glusterfs-cluster-ep
    path: takara-glus
  persistentVolumeReclaimPolicy: Retain


