apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: "gluster-heketi"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.1.90:8080"
  restuser: "admin"
  restuserkey: "admin"
