apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-vol
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
     