kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: hostpath-pvc1
 annotations:
   volume.beta.kubernetes.io/storage-class: ""
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: "30Gi"
 selector:
   matchLabels:
     name: hostpath1