apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod3
  labels:
    app: nginx-pod3
spec:
  containers:
  - name: nginx-pod
    image: gcr.io/google_containers/nginx-slim:0.8
    ports:
    - name: web
      containerPort: 80
    volumeMounts:
    - name: hostpath-vol1
      mountPath: /usr/share/nginx/html
  volumes:
  - name: hostpath-vol1
    persistentVolumeClaim:
      claimName: hostpath-pvc1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service3
spec:
  type: NodePort
  selector:
    app: nginx-pod3
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31593
    
