# apiVersion: v1
# kind: ReplicationController
#

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-nfs
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-1
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-nfs
spec:
    type: NodePort
    ports:
    - name: http
      port: 80
      nodePort: 32080
    selector:
        app: web-frontend

