---
# handlers file for Bind setup
- name: Start named
  systemd:
    name: named.service
    state: started
    enabled: yes
  become: yes

- name: ReStart named
  systemd:
    name: named.service
    state: restarted

- name: reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded
    
