# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_spec = [
  { name: "ns", cpu: 1, memory: 512,
    box: "generic/centos8",
    private_ip: "172.20.1.254",
    public_ip: "192.168.1.254",
    storage: [5,5], playbook: "install_nameserver.yml",
    comment: "dns,ca,ldap" },

  { name: "git", cpu: 1, memory: 512,
    box: "generic/centos8",    
    private_ip: "172.20.1.253",
    public_ip: "192.168.1.253",
    storage: [100], playbook: "install_git.yml",
    comment: "git repository" },

  { name: "regi", cpu: 1, memory: 512,
    box: "generic/centos8",    
    private_ip: "172.20.1.252",
    public_ip: "192.168.1.252",
    storage: [100], playbook: "install_registry.yml",
    comment: "container registry" },

  { name: "ldap", cpu: 1, memory: 512,
    box: "generic/centos7",
    #box: "centos/7",        
    private_ip: "172.20.1.251",
    public_ip: "192.168.1.251",
    storage: [], playbook: "install_ldap.yml",
    comment: "directory service" },

  { name: "jenkins", cpu: 2, memory: 2048,
    box: "generic/centos8",
    #box: "centos/8",        
    private_ip: "172.20.1.250",
    public_ip: "192.168.1.250",
    storage: [], playbook: "install_jenkins.yml",
    comment: "CI tool" },
]


Vagrant.configure("2") do |config|
  vm_spec.each do |spec|
    config.vm.define spec[:name] do |v|
      v.vm.box = spec[:box]
      v.vm.hostname = spec[:name]
      v.vm.network :private_network,ip: spec[:private_ip]
      v.vm.network :public_network,ip:  spec[:public_ip], bridge: "enp4s0"
      v.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.cpus = spec[:cpu]
        vbox.memory = spec[:memory]
        i = 1
        spec[:storage].each do |vol|
          vdisk = "vdisks/sd-" + spec[:name] + "-" + i.to_s + ".vdi"
          if not File.exist?(vdisk) then
            if i == 1 then
              vbox.customize [
                'storagectl', :id,
                '--name', 'SATA Controller',
                '--add', 'sata',
                '--controller', 'IntelAHCI']
            end            
            vbox.customize [
              'createmedium', 'disk',
              '--filename', vdisk,
              '--format', 'VDI',
              '--size', vol * 1024 ]
          end
          vbox.customize [
            'storageattach', :id,
            '--storagectl', 'SATA Controller',
            '--port', i,
            '--device', 0,
            '--type', 'hdd',
            '--medium', vdisk]
          i = i + 1
        end
      end
      v.vm.synced_folder ".", "/vagrant", owner: "vagrant",
                            group: "vagrant", mount_options: ["dmode=700", "fmode=700"]

      v.vm.provision "ansible_local" do |ansible|
        ansible.playbook       = "playbook/" + spec[:playbook]
        ansible.version        = "latest"
        ansible.verbose        = false
        ansible.install        = true
        ansible.limit          = spec[:name] 
        ansible.inventory_path = "playbook/hosts"
      end
    
      # v.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   apt-get install -y apache2
      # SHELL
    end
  end
end
