# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", ip: "192.168.1.98", bridge: "en0: Ethernet"

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     #vb.gui = true
     vb.memory = "512"
  end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y nfs-kernel-server
     mkdir /export -p
     chown nobody:nogroup /export
     echo Hello from NFS Server > /export/index.html
     chmod a+r /export/index.html

cat - > /etc/exports <<EOF
/export *(rw,sync,no_root_squash,no_subtree_check)
EOF

     service nfs-kernel-server restart      
  SHELL
end
