apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web
        image: maho/webserver:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver1
spec:
  type: NodePort
  selector:
    app: web1
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31080


