# tasks file for Docker setup

## Container Registry

- name: Container Registry Create a ext4 filesystem on /dev/sdb and check disk blocks
  filesystem:
    fstype: ext4
    dev: /dev/sdb

- name: Mount up device by /dev/sdc
  mount:
    path: "{{ registry_dir }}"
    src:  /dev/sdb
    fstype: ext4
    state: mounted


- name: ensure a list of packages uninstalled
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

    
- name: Add Docker repository
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo
    

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - docker-ce-3:18.09.0-3.el7
    - docker-ce-cli-1:18.09.0-3.el7
    - containerd.io

- name: Add the user 'vagrant' with a specific uid and a primary group of 'docker'
  user:
    name: vagrant
    comment: docker exection user
    group: docker

- name: Start dockerd
  systemd:
    name: docker
    state: started
  become: yes


