apiVersion: v1
kind: Pod
metadata:
  name: nginx-z3
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx.conf
        items:
        - key: nginx.conf
          path: nginx.conf
  restartPolicy: Never


