apiVersion: v1
kind: Pod
metadata:
  name: nginx-w-configmap
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-config
  restartPolicy: Never
