apiVersion: v1
kind: Pod
metadata:
  name: pod-shell
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: apl-config-vol
      mountPath: /etc/config
    - name: apl-kanji-config-vol
      mountPath: /etc/config-kanji
  volumes:
    - name: apl-config-vol
      configMap:
        name: apl-config
    - name: apl-kanji-config-vol
      configMap:
        name: apl-kanji-config
  restartPolicy: Never  