apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myadmin

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend

    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          value: "mysql"

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: web-phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31580
