- hosts: nfsserver
  connection: local
  become: yes

  tasks:
    - name: Create export dir
      file: path=/export state=directory mode=777 owner=root group=root

    - name: Ensure NFS utilities are installed.
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - nfs-common
        - nfs-kernel-server

    - name: copy /etc/exports
      template: src=/vagrant/exports.tmp dest=/etc/exports owner=root group=root

    - name: restart nfs server
      service: name=nfs-kernel-server state=restarted