version: '3'
services:
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile.web
        volumes:
            - ./data/www:/var/www
        ports:
            - "8090:80"
        links:
            - app
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile.app
        volumes:
            - ./data/www:/var/www
        environment:
            - DB_USER=root
            - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
        links:
            - mysql
            - redis
        depends_on:
            - mysql
            - redis

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8095:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/mysql_init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"

    redis:
        restart: always
        image: redis:latest
        volumes:
            - ./data/redis:/data
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
